<a href="https://colab.research.google.com/github/B34R-e/Basic-Machine-Learning/blob/main/Application_of_Cosine_Similarity_in_a_Recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math

Laptop = 1
Tablet = 2
Headphones = 3
Keyboard = 4
Mouse = 5

Alice = np.array([Tablet, Laptop, Headphones, Mouse, Keyboard, Laptop, Headphones, Headphones, Mouse, Tablet])
Bob = np.array([Mouse, Laptop, Tablet, Laptop, Keyboard])
Carol = np.array([Tablet, Laptop, Keyboard, Headphones, Headphones])

In [ ]:
import numpy as np
import math

Laptop = 1
Tablet = 2
Headphones = 3
Keyboard = 4
Mouse = 5

Alice = np.array([Tablet, Laptop, Headphones, Mouse, Keyboard, Laptop, Headphones, Headphones, Mouse, Tablet])
Bob = np.array([Mouse, Laptop, Tablet, Laptop, Keyboard])
Carol = np.array([Tablet, Laptop, Keyboard, Headphones, Headphones])

In [ ]:
def slicing(list, number_of_slices):
  list_of_slices = []
  for i in range(len(list) - number_of_slices):
    list_of_slices.append(list[i : i + number_of_slices])
  return list_of_slices

slicing(Alice, 5)

[array([2, 1, 3, 5, 4]),
 array([1, 3, 5, 4, 1]),
 array([3, 5, 4, 1, 3]),
 array([5, 4, 1, 3, 3]),
 array([4, 1, 3, 3, 5])]

In [ ]:
from numpy.linalg import norm
def calc_cosine_using_formula(X, Y):
  return (X.dot(Y)) / (norm(X) * norm(Y))

In [ ]:
cosine_similarity_of_Bob_to_Alice = []
for each in slicing(Alice, 5):
  cosine_similarity_of_Bob_to_Alice.append(calc_cosine_using_formula(Bob, each))

print(cosine_similarity_of_Bob_to_Alice)

[0.747400394766227, 0.5259237061407777, 0.7720746665835772, 0.8662301137279158, 0.9415544714433868]


In [ ]:
cosine_similarity_of_Carol_to_Alice = []
for each in slicing(Alice, 5):
  cosine_similarity_of_Carol_to_Alice.append(calc_cosine_using_formula(each, Carol))

print(cosine_similarity_of_Carol_to_Alice)

[0.950033737592567, 0.8882311833686551, 0.8062257748298549, 0.7442084075352506, 0.9302605094190634]


In [ ]:
def slicing(list, number_of_slices):
  list_of_slices = []
  for i in range(len(list) - number_of_slices):
    list_of_slices.append(list[i : i + number_of_slices])
  return list_of_slices

slicing(Alice, 5)

[array([2, 1, 3, 5, 4]),
 array([1, 3, 5, 4, 1]),
 array([3, 5, 4, 1, 3]),
 array([5, 4, 1, 3, 3]),
 array([4, 1, 3, 3, 5])]

In [ ]:
from numpy.linalg import norm
def calc_cosine_using_formula(X, Y):
  return (X.dot(Y)) / (norm(X) * norm(Y))

In [ ]:
cosine_similarity_of_Bob_to_Alice = []
for each in slicing(Alice, 5):
  cosine_similarity_of_Bob_to_Alice.append(calc_cosine_using_formula(Bob, each))

print(cosine_similarity_of_Bob_to_Alice)

[0.747400394766227, 0.5259237061407777, 0.7720746665835772, 0.8662301137279158, 0.9415544714433868]


In [ ]:
cosine_similarity_of_Carol_to_Alice = []
for each in slicing(Alice, 5):
  cosine_similarity_of_Carol_to_Alice.append(calc_cosine_using_formula(each, Carol))

print(cosine_similarity_of_Carol_to_Alice)

[0.950033737592567, 0.8882311833686551, 0.8062257748298549, 0.7442084075352506, 0.9302605094190634]
